# Generated by Django 4.2.4 on 2023-09-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="father",
            field=models.TextField(default="Rahim"),
        ),
    ]
